package com.uc4.ara.feature.logcollector.test;

import com.uc4.ara.feature.logcollector.functions.DateFormatParser;
import junit.framework.TestCase;

import java.util.Date;

/**
 * The class <code>DateFormatParserTest</code> contains tests for the class
 * {@link <code>DateFormatParser</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 20.06.13 14:22
 *
 * @author extsts
 *
 * @version $Revision$
 */
public class DateFormatParserTest extends TestCase {

	private DateFormatParser parser;
	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public DateFormatParserTest(String name) {
		super(name);
	}

	/**
	 * Perform pre-test initialization
	 *
	 * @throws Exception
	 *
	 * @see TestCase#setUp()
	 */
	protected void setUp() throws Exception {
		super.setUp();

		String commaSeparatedDates = "yyyy.MM.dd HH:mm:ss, dd.MM.yyyy HH:mm:ss, MM/dd/yyyy HH:mm:ss, MM-dd-yyyy HH:mm:ss, dd-MM-yyyy HH:mm:ss";
		parser = new DateFormatParser(commaSeparatedDates);
	}

	/**
	 * Perform post-test clean up
	 *
	 * @throws Exception
	 *
	 * @see TestCase#tearDown()
	 */
	protected void tearDown() throws Exception {
		super.tearDown();
		// Add additional tear down code here
	}

	/**
	 * Run the Date getDateFromString(String) method test
	 */
	public void testGetEuropeDateFromString() {
		String dateString = "01.01.2013 13:15:53";
		Date expectedDate = new Date();
		expectedDate.setYear(113);
		expectedDate.setDate(1);
		expectedDate.setMonth(0);
		expectedDate.setHours(13);
		expectedDate.setMinutes(15);
		expectedDate.setSeconds(53);
		Date date = parser.getDateFromString(dateString);

		assertEquals(expectedDate.toString(), date.toString());
	}

	public void testGetUSDateFromString() {
		String dateString = "12.31.2013 13:15:53";
		Date expectedDate = new Date();
		expectedDate.setYear(113);
		expectedDate.setDate(31);
		expectedDate.setMonth(11);
		expectedDate.setHours(13);
		expectedDate.setMinutes(15);
		expectedDate.setSeconds(53);
		Date date = parser.getDateFromString(dateString);

		assertEquals(expectedDate.toString(), date.toString());
	}

	/**
	 * Run the boolean isValidDateFormat(String) method test
	 */
	public void testIsValidEuropeDateFormat() {
		String dateString = "01.01.2013 13:15:53";
		assertEquals(true, parser.isValidDateFormat(dateString));
	}

	public void testIsValidUSDateFormat() {
		String dateString = "12.31.2013 13:15:53";
		assertEquals(true, parser.isValidDateFormat(dateString));
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames =
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = true
 * createTearDown = true
 * createTestFixture = false
 * createTestStubs = false
 * methods = getDateFromString(QString;),isValidDateFormat(QString;)
 * package = com.uc4.ara.feature.logcollector.test
 * package.sourceFolder = ARATools 4.LOW/src
 * superclassType = junit.framework.TestCase
 * testCase = DateFormatParserTest
 * testClassType = com.uc4.ara.feature.logcollector.functions.DateFormatParser
 */
